server:
  port: 50051
  base_url: http://localhost:8080/

storage:
  # Available options: memory, redis, postgres, both (both redis and postgres)
  type: both
  redis_url: redis://localhost:6380
  postgres:
    host: localhost
    port: 5433
    user: postgres
    password: postgres
    dbname: shortlink
    sslmode: disable
    max_open_conns: 25
    max_idle_conns: 5
    conn_max_lifetime: 15m
  cache_ttl: 3600 # seconds

snowflake:
  machine_id: 1 

# OpenTelemetry configuration
telemetry:
  enabled: true
  otlp_endpoint: "localhost:4318"  # Only specify host:port, path will be added by the client
  service_name: "shortlink-core"
  environment: "dev" 