services:
  # PostgreSQL database service
  postgres:
    image: postgres:14.7
    container_name: shortlink-postgres
    environment:
      POSTGRES_DB: shortlink
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_INITDB_ARGS: "--auth=md5" # 強制 md5 而非 scram-sha-256
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    networks:
      - shortlink-network
    # image: postgres:14.7
    # ports:
    #   - "5432:5432"
    # environment:
    #   LC_COLLATE: 'en_US.UTF-8'
    #   POSTGRES_DB: gama
    #   POSTGRES_USER: gama
    #   POSTGRES_PASSWORD: gama
    #   PGDATA: /var/lib/postgresql/data/pgdata
    # volumes:
    #   - gamaacct_db_data:/var/lib/postgresql/data
    # Redis cache service
  redis:
    image: redis:latest
    container_name: shortlink-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    networks:
      - shortlink-network
  # Shortlink Core service (uncomment to enable)
  # shortlink-core:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   container_name: shortlink-core
  #   depends_on:
  #     postgres:
  #       condition: service_healthy
  #     redis:
  #       condition: service_healthy
  #   environment:
  #     SHORTLINK_STORAGE_TYPE: both
  #     # New PostgreSQL configuration
  #     SHORTLINK_STORAGE_POSTGRES_HOST: postgres
  #     SHORTLINK_STORAGE_POSTGRES_PORT: 5432
  #     SHORTLINK_STORAGE_POSTGRES_USER: postgres
  #     SHORTLINK_STORAGE_POSTGRES_PASSWORD: postgres
  #     SHORTLINK_STORAGE_POSTGRES_DBNAME: shortlink
  #     SHORTLINK_STORAGE_POSTGRES_SSLMODE: disable
  #     SHORTLINK_STORAGE_POSTGRES_MAX_OPEN_CONNS: 25
  #     SHORTLINK_STORAGE_POSTGRES_MAX_IDLE_CONNS: 5
  #     SHORTLINK_STORAGE_POSTGRES_CONN_MAX_LIFETIME: 15m
  #     # Redis configuration
  #     SHORTLINK_STORAGE_REDIS_URL: redis://redis:6379
  #     SHORTLINK_SERVER_PORT: 50051
  #     SHORTLINK_SERVER_BASE_URL: "http://localhost:8080/"
  #   ports:
  #     - "50051:50051"
  #   restart: unless-stopped
  #   networks:
  #     - shortlink-network

networks:
  shortlink-network:
    driver: bridge

volumes:
  postgres_data: # gamaacct_db_data:

  redis_data:
