// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"context"
	"database/sql"
	"fmt"
)

type DBTX interface {
	ExecContext(context.Context, string, ...interface{}) (sql.Result, error)
	PrepareContext(context.Context, string) (*sql.Stmt, error)
	QueryContext(context.Context, string, ...interface{}) (*sql.Rows, error)
	QueryRowContext(context.Context, string, ...interface{}) *sql.Row
}

func New(db DBTX) *Queries {
	return &Queries{db: db}
}

func Prepare(ctx context.Context, db DBTX) (*Queries, error) {
	q := Queries{db: db}
	var err error
	if q.findShortIDByURLStmt, err = db.PrepareContext(ctx, findShortIDByURL); err != nil {
		return nil, fmt.Errorf("error preparing query FindShortIDByURL: %w", err)
	}
	if q.getURLStmt, err = db.PrepareContext(ctx, getURL); err != nil {
		return nil, fmt.Errorf("error preparing query GetURL: %w", err)
	}
	if q.storeWithIDStmt, err = db.PrepareContext(ctx, storeWithID); err != nil {
		return nil, fmt.Errorf("error preparing query StoreWithID: %w", err)
	}
	return &q, nil
}

func (q *Queries) Close() error {
	var err error
	if q.findShortIDByURLStmt != nil {
		if cerr := q.findShortIDByURLStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing findShortIDByURLStmt: %w", cerr)
		}
	}
	if q.getURLStmt != nil {
		if cerr := q.getURLStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getURLStmt: %w", cerr)
		}
	}
	if q.storeWithIDStmt != nil {
		if cerr := q.storeWithIDStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing storeWithIDStmt: %w", cerr)
		}
	}
	return err
}

func (q *Queries) exec(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) (sql.Result, error) {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).ExecContext(ctx, args...)
	case stmt != nil:
		return stmt.ExecContext(ctx, args...)
	default:
		return q.db.ExecContext(ctx, query, args...)
	}
}

func (q *Queries) query(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) (*sql.Rows, error) {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).QueryContext(ctx, args...)
	case stmt != nil:
		return stmt.QueryContext(ctx, args...)
	default:
		return q.db.QueryContext(ctx, query, args...)
	}
}

func (q *Queries) queryRow(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) *sql.Row {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).QueryRowContext(ctx, args...)
	case stmt != nil:
		return stmt.QueryRowContext(ctx, args...)
	default:
		return q.db.QueryRowContext(ctx, query, args...)
	}
}

type Queries struct {
	db                   DBTX
	tx                   *sql.Tx
	findShortIDByURLStmt *sql.Stmt
	getURLStmt           *sql.Stmt
	storeWithIDStmt      *sql.Stmt
}

func (q *Queries) WithTx(tx *sql.Tx) *Queries {
	return &Queries{
		db:                   tx,
		tx:                   tx,
		findShortIDByURLStmt: q.findShortIDByURLStmt,
		getURLStmt:           q.getURLStmt,
		storeWithIDStmt:      q.storeWithIDStmt,
	}
}
